Tighter shell integration
* eat.el (eat--t-term): New slots: 'prompt-start-fn',
'prompt-end-fn', 'cont-prompt-start-fn', 'cont-prompt-end-fn',
'set-cmd-fn', 'cmd-start-fn', 'cmd-finish-fn'
* eat.el (eat--t-set-cwd): Accept three arguments in two
different formats.
* eat.el (eat--t-prompt-start, eat--t-prompt-end)
(eat--t-cont-prompt-start, eat--t-cont-prompt-end)
(eat--t-set-cmd, eat--t-cmd-start, eat--t-cmd-finish): New
function.
* eat.el (eat--t-handle-output): Accept Eat's own
OSC 51 ; e ; ... ST sequences.
* eat.el (eat-term-prompt-start-function)
(eat-term-prompt-end-function)
(eat-term-continuation-prompt-start-function)
(eat-term-continuation-prompt-end-function)
(eat-term-set-cmd-function, eat-term-cmd-start-function)
(eat-term-cmd-finish-function): New generalized variable.
* integration/bash (__eat_current_command, __eat_exit_status):
New variable.
* integration/bash (__eat_prompt_command): Send exit status of
last command, if applicable.  Use Eat specific sequence to
report working directory.  Set title.
* integration/bash (__eat_preexec): Report current command and
execution start.
* integration/bash (__eat_before_prompt_command): Set
'__eat_exit_status' to the exit status of the last command.
* integration/bash (__eat_prompt_start, __eat_prompt_end)
(__eat_continuation_start, __eat_continuation_end): New
variable, used as constant only to make the code more readable.
* integration/bash (__eat_enable_integration): Wrap 'PS1' and
'PS2'.  Don't set title from 'PS1'.

diff --git a/integration/bash b/integration/bash
--- a/integration/bash
+++ b/integration/bash
@@ -17,26 +17,49 @@
 # For a full copy of the GNU General Public License
 # see <https://www.gnu.org/licenses/>.
 
+__eat_current_command=""
+__eat_exit_status=0
+
 __eat_prompt_command () {
+  # Send exit status.
+  if test -n "$__eat_current_command"
+  then
+    printf '\e]51;e;H;%i\e\\' "$__eat_exit_status"
+  fi
+  __eat_current_command=""
   # Send the current working directory, for directory tracking.
-  printf '\e]7;file://%s%s\e\\' "$HOSTNAME" "$PWD"
+  printf '\e]51;e;A;%s;%s\e\\' "$(printf "%s" "$HOSTNAME" | base64)" \
+         "$(printf "%s" "$PWD" | base64)"
+  # Update title.
+  # "${PWD/$HOME/'~'}" converts "/home/akib/org/" to "~/org/".
+  # The next one is substituted with '$', or '#' if we're "root".
+  printf '\e]2;%s@%s:%s%s\e\\' "$USER" "$HOSTNAME" \
+         "${PWD/$HOME/'~'}" \
+         "$(test $UID -eq 0 && echo '#' || echo '$')"
 }
 
 __eat_preexec () {
+  # Get the real command typed by the user from the history.
+  __eat_current_command="$(history 1 | sed 's/ *[0-9]* *//')"
+  # Send current command.
+  printf '\e]51;e;F;%s\e\\' \
+         "$(printf "%s" "$__eat_current_command" | base64)"
+  # Send pre-exec sequence.
+  printf '\e]51;e;G\e\\'
+  # Update title to including the command running.
   # "${PWD/$HOME/'~'}" converts "/home/akib/org/" to "~/org/".
   # The next one is substituted with '$', or '#' if we're "root".
-  # The final one gets the real command typed by the user from the
-  # history.
   printf '\e]2;%s@%s:%s%s %s\e\\' "$USER" "$HOSTNAME" \
          "${PWD/$HOME/'~'}" \
          "$(test $UID -eq 0 && echo '#' || echo '$')" \
-         "$(history 1 | sed 's/ *[0-9]* *//')"
+         "$__eat_current_command"
 }
 
 __eat_inhibit_preexec=yes
 
 __eat_before_prompt_command ()
 {
+  __eat_exit_status="$?"
   __eat_inhibit_preexec=yes
 }
 
@@ -54,10 +77,16 @@ __eat_before_exec () {
   fi
 }
 
+__eat_prompt_start='\e]51;e;B\e\\'
+__eat_prompt_end='\e]51;e;C\e\\'
+__eat_continuation_start='\e]51;e;D\e\\'
+__eat_continuation_end='\e]51;e;E\e\\'
+
 __eat_enable_integration ()
 {
   __eat_integration_enabled=yes
-  PS1='\[\e]2;\u@\h:\w$\e\\\]'"$PS1"
+  PS1="\[$__eat_prompt_start\]$PS1\[$__eat_prompt_end\]"
+  PS2="\[$__eat_continuation_start\]$PS2\[$__eat_continuation_end\]"
   PROMPT_COMMAND+=(__eat_prompt_command)
   trap '__eat_before_exec' DEBUG
   # Wrap 'PROMPT_COMMAND' to avoid it getting trapped in 'DEBUG' trap.
